sudo: true
language: node_js
node_js:
  - "8"
services:
  - mongodb
env:
  - NODE_ENV=test CXX=g++-4.8
before_install:
  - sudo apt-get install unicode-data
after_script:
  - lab -r lcov | /home/travis/build/hicsail/anchor/node_modules/coveralls/bin/coveralls.js
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
