version: 2
jobs:
  build:
    working_directory: ~/anchor
    docker:
      - image: node:8
      - image: mongo:3.4.5
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - .node_modules
      - run:
          name: test
          command: npm test
      - deployment:
          staging:
            branch: master
              heroku:
                appname: get-anchor