version: 2
jobs:
  build:
    working_directory: ~/anchor
    docker:
      - image: node:8
      - image: mongo:3.4.5
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - .node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: Add ssh key to know_hosts
          command: ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
      - run:
          name: install rsync
          command: apt install rsync
      - deploy:
          name: Deploy
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                rm -rf node_modules && rsync -r ./* $SERVER_USER@$SERVER_IP:/home/$SERVER_USER/$PROJECT_NAME/
                ssh $SERVER_USER@$SERVER_IP 'cd /home/$SERVER_USER/$PROJECT_NAME && docker-compose build && docker-compose up -d'
              fi
